networks:
  mynetworkapi:

services:
    sqlserverdocker:
     container_name: sql-server-docker
     image: mcr.microsoft.com/mssql/server:2022-latest
     ports:
      - 8006:1433
     environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=UEUA2025mj!*
     networks:
      - mynetworkapi

    api.unidademprendimiento:
     image: ${DOCKER_REGISTRY-}apiunidademprendimiento
     build:
      context: .
      dockerfile: src/API/Api.UnidadEmprendimiento/Dockerfile
     networks:
      - mynetworkapi
     depends_on:
      - sqlserverdocker
     ports:
      - 5001:8081

     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionDB=Server=sqlserverdocker,1433;Database=UNIDADEMPRENDIMIENTO;User Id=sa;Password=UEUA2025mj!*;MultipleActiveResultSets=True;TrustServerCertificate=True;
     command: 
      - /bin/bash
      - -c
      - |
        until dotnet ef database update; do 
        echo 'Esperando a SQL Server...'; 
        sleep 5; 
        done

